/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DetailedProjectsRouteImport } from './routes/_detailed-projects'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DetailedProjectsVesselviewRouteImport } from './routes/_detailed-projects/vesselview'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailedProjectsRoute = DetailedProjectsRouteImport.update({
  id: '/_detailed-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailedProjectsVesselviewRoute =
  DetailedProjectsVesselviewRouteImport.update({
    id: '/vesselview',
    path: '/vesselview',
    getParentRoute: () => DetailedProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/skills': typeof SkillsRoute
  '/vesselview': typeof DetailedProjectsVesselviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/skills': typeof SkillsRoute
  '/vesselview': typeof DetailedProjectsVesselviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_detailed-projects': typeof DetailedProjectsRouteWithChildren
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/skills': typeof SkillsRoute
  '/_detailed-projects/vesselview': typeof DetailedProjectsVesselviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/projects' | '/skills' | '/vesselview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/projects' | '/skills' | '/vesselview'
  id:
    | '__root__'
    | '/'
    | '/_detailed-projects'
    | '/contact'
    | '/projects'
    | '/skills'
    | '/_detailed-projects/vesselview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DetailedProjectsRoute: typeof DetailedProjectsRouteWithChildren
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRoute
  SkillsRoute: typeof SkillsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_detailed-projects': {
      id: '/_detailed-projects'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DetailedProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_detailed-projects/vesselview': {
      id: '/_detailed-projects/vesselview'
      path: '/vesselview'
      fullPath: '/vesselview'
      preLoaderRoute: typeof DetailedProjectsVesselviewRouteImport
      parentRoute: typeof DetailedProjectsRoute
    }
  }
}

interface DetailedProjectsRouteChildren {
  DetailedProjectsVesselviewRoute: typeof DetailedProjectsVesselviewRoute
}

const DetailedProjectsRouteChildren: DetailedProjectsRouteChildren = {
  DetailedProjectsVesselviewRoute: DetailedProjectsVesselviewRoute,
}

const DetailedProjectsRouteWithChildren =
  DetailedProjectsRoute._addFileChildren(DetailedProjectsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DetailedProjectsRoute: DetailedProjectsRouteWithChildren,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRoute,
  SkillsRoute: SkillsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
